{{- if eq (include "turbo-vector.createS3CredentialsSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "turbo-vector.storageS3CredentialsSecretName" . }}
  labels:
    {{- include "turbo-vector.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if eq (include "turbo-vector.storageMode" .) "rustfs" }}
  {{ .Values.rustfs.credentials.accessKeyField }}: {{ .Values.rustfs.credentials.accessKey | quote }}
  {{ .Values.rustfs.credentials.secretKeyField }}: {{ .Values.rustfs.credentials.secretKey | quote }}
  {{- else }}
  {{ .Values.storage.s3.accessKeyField }}: {{ .Values.storage.s3.accessKey | quote }}
  {{ .Values.storage.s3.secretKeyField }}: {{ .Values.storage.s3.secretKey | quote }}
  {{- end }}
{{- end }}
