# coding: utf-8

"""
    turbo-vector-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict
from pydantic import BaseModel, Field, conint

class CollectionStatsResponse(BaseModel):
    """
    CollectionStatsResponse
    """
    dimension: conint(strict=True, ge=0) = Field(...)
    generation: conint(strict=True, ge=0) = Field(...)
    segments: conint(strict=True, ge=0) = Field(...)
    vector_count: conint(strict=True, ge=0) = Field(...)
    additional_properties: Dict[str, Any] = {}
    __properties = ["dimension", "generation", "segments", "vector_count"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CollectionStatsResponse:
        """Create an instance of CollectionStatsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "additional_properties"
                          },
                          exclude_none=True)
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CollectionStatsResponse:
        """Create an instance of CollectionStatsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CollectionStatsResponse.parse_obj(obj)

        _obj = CollectionStatsResponse.parse_obj({
            "dimension": obj.get("dimension"),
            "generation": obj.get("generation"),
            "segments": obj.get("segments"),
            "vector_count": obj.get("vector_count")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


