# coding: utf-8

"""
    turbo-vector-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, Optional
from pydantic import BaseModel, Field, StrictStr, conint
from turbo_vector_sdk.models.metric import Metric

class CreateCollectionRequest(BaseModel):
    """
    CreateCollectionRequest
    """
    dimension: conint(strict=True, ge=0) = Field(...)
    metadata_schema: Optional[Any] = None
    metric: Optional[Metric] = None
    name: StrictStr = Field(...)
    additional_properties: Dict[str, Any] = {}
    __properties = ["dimension", "metadata_schema", "metric", "name"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CreateCollectionRequest:
        """Create an instance of CreateCollectionRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "additional_properties"
                          },
                          exclude_none=True)
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if metadata_schema (nullable) is None
        # and __fields_set__ contains the field
        if self.metadata_schema is None and "metadata_schema" in self.__fields_set__:
            _dict['metadata_schema'] = None

        # set to None if metric (nullable) is None
        # and __fields_set__ contains the field
        if self.metric is None and "metric" in self.__fields_set__:
            _dict['metric'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CreateCollectionRequest:
        """Create an instance of CreateCollectionRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CreateCollectionRequest.parse_obj(obj)

        _obj = CreateCollectionRequest.parse_obj({
            "dimension": obj.get("dimension"),
            "metadata_schema": obj.get("metadata_schema"),
            "metric": obj.get("metric"),
            "name": obj.get("name")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


