# coding: utf-8

"""
    turbo-vector-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, List
from pydantic import BaseModel, Field, StrictStr, conlist
from turbo_vector_sdk.models.fetch_vector import FetchVector

class FetchResponse(BaseModel):
    """
    FetchResponse
    """
    namespace: StrictStr = Field(...)
    vectors: conlist(FetchVector) = Field(...)
    additional_properties: Dict[str, Any] = {}
    __properties = ["namespace", "vectors"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> FetchResponse:
        """Create an instance of FetchResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "additional_properties"
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in vectors (list)
        _items = []
        if self.vectors:
            for _item in self.vectors:
                if _item:
                    _items.append(_item.to_dict())
            _dict['vectors'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> FetchResponse:
        """Create an instance of FetchResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return FetchResponse.parse_obj(obj)

        _obj = FetchResponse.parse_obj({
            "namespace": obj.get("namespace"),
            "vectors": [FetchVector.from_dict(_item) for _item in obj.get("vectors")] if obj.get("vectors") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


