# coding: utf-8

"""
    turbo-vector-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class OperationApplyStatus(str, Enum):
    """
    OperationApplyStatus
    """

    """
    allowed enum values
    """
    ACCEPTED = 'accepted'
    APPLIED = 'applied'

    @classmethod
    def from_json(cls, json_str: str) -> OperationApplyStatus:
        """Create an instance of OperationApplyStatus from a JSON string"""
        return OperationApplyStatus(json.loads(json_str))


