# coding: utf-8

"""
    turbo-vector-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr, conint, conlist

class QueryAnnObservability(BaseModel):
    """
    QueryAnnObservability
    """
    ann_fallback_count: conint(strict=True, ge=0) = Field(...)
    ann_fetch_errors: conint(strict=True, ge=0) = Field(...)
    ann_used: StrictBool = Field(...)
    buckets_probed: conint(strict=True, ge=0) = Field(...)
    candidates_scored: conint(strict=True, ge=0) = Field(...)
    fallback_reasons: Optional[conlist(StrictStr)] = None
    filter_cluster_cache_evictions: Optional[conint(strict=True, ge=0)] = None
    filter_cluster_cache_hits: Optional[conint(strict=True, ge=0)] = None
    filter_cluster_cache_misses: Optional[conint(strict=True, ge=0)] = None
    filter_row_cache_evictions: Optional[conint(strict=True, ge=0)] = None
    filter_row_cache_hits: Optional[conint(strict=True, ge=0)] = None
    filter_row_cache_misses: Optional[conint(strict=True, ge=0)] = None
    filter_widen_passes: Optional[conint(strict=True, ge=0)] = None
    additional_properties: Dict[str, Any] = {}
    __properties = ["ann_fallback_count", "ann_fetch_errors", "ann_used", "buckets_probed", "candidates_scored", "fallback_reasons", "filter_cluster_cache_evictions", "filter_cluster_cache_hits", "filter_cluster_cache_misses", "filter_row_cache_evictions", "filter_row_cache_hits", "filter_row_cache_misses", "filter_widen_passes"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> QueryAnnObservability:
        """Create an instance of QueryAnnObservability from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "additional_properties"
                          },
                          exclude_none=True)
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> QueryAnnObservability:
        """Create an instance of QueryAnnObservability from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return QueryAnnObservability.parse_obj(obj)

        _obj = QueryAnnObservability.parse_obj({
            "ann_fallback_count": obj.get("ann_fallback_count"),
            "ann_fetch_errors": obj.get("ann_fetch_errors"),
            "ann_used": obj.get("ann_used"),
            "buckets_probed": obj.get("buckets_probed"),
            "candidates_scored": obj.get("candidates_scored"),
            "fallback_reasons": obj.get("fallback_reasons"),
            "filter_cluster_cache_evictions": obj.get("filter_cluster_cache_evictions"),
            "filter_cluster_cache_hits": obj.get("filter_cluster_cache_hits"),
            "filter_cluster_cache_misses": obj.get("filter_cluster_cache_misses"),
            "filter_row_cache_evictions": obj.get("filter_row_cache_evictions"),
            "filter_row_cache_hits": obj.get("filter_row_cache_hits"),
            "filter_row_cache_misses": obj.get("filter_row_cache_misses"),
            "filter_widen_passes": obj.get("filter_widen_passes")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


