# coding: utf-8

"""
    turbo-vector-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, List
from pydantic import BaseModel, Field, StrictStr, conlist
from turbo_vector_sdk.models.query_ann_observability import QueryAnnObservability
from turbo_vector_sdk.models.query_match import QueryMatch

class QueryResponse(BaseModel):
    """
    QueryResponse
    """
    ann: QueryAnnObservability = Field(...)
    matches: conlist(QueryMatch) = Field(...)
    namespace: StrictStr = Field(...)
    additional_properties: Dict[str, Any] = {}
    __properties = ["ann", "matches", "namespace"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> QueryResponse:
        """Create an instance of QueryResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "additional_properties"
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of ann
        if self.ann:
            _dict['ann'] = self.ann.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in matches (list)
        _items = []
        if self.matches:
            for _item in self.matches:
                if _item:
                    _items.append(_item.to_dict())
            _dict['matches'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> QueryResponse:
        """Create an instance of QueryResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return QueryResponse.parse_obj(obj)

        _obj = QueryResponse.parse_obj({
            "ann": QueryAnnObservability.from_dict(obj.get("ann")) if obj.get("ann") is not None else None,
            "matches": [QueryMatch.from_dict(_item) for _item in obj.get("matches")] if obj.get("matches") is not None else None,
            "namespace": obj.get("namespace")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


