# coding: utf-8

"""
    turbo-vector-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class QuerySearchStrategy(str, Enum):
    """
    QuerySearchStrategy
    """

    """
    allowed enum values
    """
    AUTO = 'auto'
    EXACT = 'exact'
    ANN = 'ann'

    @classmethod
    def from_json(cls, json_str: str) -> QuerySearchStrategy:
        """Create an instance of QuerySearchStrategy from a JSON string"""
        return QuerySearchStrategy(json.loads(json_str))


