# coding: utf-8

"""
    turbo-vector-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, List, Optional, Union
from pydantic import BaseModel, Field, StrictBool, StrictFloat, StrictInt, StrictStr, conint, conlist
from turbo_vector_sdk.models.query_search_strategy import QuerySearchStrategy

class QueryRequest(BaseModel):
    """
    QueryRequest
    """
    filter: Optional[Any] = None
    include_metadata: Optional[StrictBool] = None
    include_values: Optional[StrictBool] = None
    namespace: Optional[StrictStr] = None
    search_strategy: Optional[QuerySearchStrategy] = None
    top_k: Optional[conint(strict=True, ge=0)] = None
    vector: conlist(Union[StrictFloat, StrictInt]) = Field(...)
    additional_properties: Dict[str, Any] = {}
    __properties = ["filter", "include_metadata", "include_values", "namespace", "search_strategy", "top_k", "vector"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> QueryRequest:
        """Create an instance of QueryRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "additional_properties"
                          },
                          exclude_none=True)
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if filter (nullable) is None
        # and __fields_set__ contains the field
        if self.filter is None and "filter" in self.__fields_set__:
            _dict['filter'] = None

        # set to None if namespace (nullable) is None
        # and __fields_set__ contains the field
        if self.namespace is None and "namespace" in self.__fields_set__:
            _dict['namespace'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> QueryRequest:
        """Create an instance of QueryRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return QueryRequest.parse_obj(obj)

        _obj = QueryRequest.parse_obj({
            "filter": obj.get("filter"),
            "include_metadata": obj.get("include_metadata"),
            "include_values": obj.get("include_values"),
            "namespace": obj.get("namespace"),
            "search_strategy": obj.get("search_strategy"),
            "top_k": obj.get("top_k"),
            "vector": obj.get("vector")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


