# coding: utf-8

"""
    turbo-vector-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, Optional, Union
from pydantic import BaseModel, Field, StrictBool, StrictFloat, StrictInt, StrictStr, conint
from turbo_vector_sdk.models.filter_cache_metrics_snapshot import FilterCacheMetricsSnapshot

class RuntimeConfigResponse(BaseModel):
    """
    RuntimeConfigResponse
    """
    ann_bucket_fetch_concurrency: conint(strict=True, ge=0) = Field(...)
    bind_addr: StrictStr = Field(...)
    filter_cache_metrics: Optional[FilterCacheMetricsSnapshot] = None
    filter_cluster_cache_max_bytes: conint(strict=True, ge=0) = Field(...)
    filter_cluster_cache_max_entries: conint(strict=True, ge=0) = Field(...)
    filter_max_glob_bytes: conint(strict=True, ge=0) = Field(...)
    filter_max_regex_bytes: conint(strict=True, ge=0) = Field(...)
    filter_max_widen_passes: conint(strict=True, ge=0) = Field(...)
    filter_row_cache_max_bytes: conint(strict=True, ge=0) = Field(...)
    filter_row_cache_max_entries: conint(strict=True, ge=0) = Field(...)
    fts_block_merge_threshold: conint(strict=True, ge=0) = Field(...)
    fts_block_split_threshold: conint(strict=True, ge=0) = Field(...)
    fts_block_target_postings: conint(strict=True, ge=0) = Field(...)
    fts_enable_delta_rebalance: StrictBool = Field(...)
    fts_max_term_blocks_touched_per_doc_update: conint(strict=True, ge=0) = Field(...)
    otel_enabled: StrictBool = Field(...)
    otel_exporter_otlp_endpoint: StrictStr = Field(...)
    otel_metric_export_interval_ms: conint(strict=True, ge=0) = Field(...)
    otel_sample_ratio: Union[StrictFloat, StrictInt] = Field(...)
    otel_service_name: StrictStr = Field(...)
    query_ann_enabled: StrictBool = Field(...)
    queue_broker_url: StrictStr = Field(...)
    storage_bucket: StrictStr = Field(...)
    storage_endpoint: StrictStr = Field(...)
    storage_provider: StrictStr = Field(...)
    storage_region: StrictStr = Field(...)
    storage_simulated_latency_ms: conint(strict=True, ge=0) = Field(...)
    wal_queue_background_drain_enabled: StrictBool = Field(...)
    wal_queue_background_drain_interval_ms: conint(strict=True, ge=0) = Field(...)
    wal_worker_build_ann: StrictBool = Field(...)
    wal_worker_build_fts: StrictBool = Field(...)
    additional_properties: Dict[str, Any] = {}
    __properties = ["ann_bucket_fetch_concurrency", "bind_addr", "filter_cache_metrics", "filter_cluster_cache_max_bytes", "filter_cluster_cache_max_entries", "filter_max_glob_bytes", "filter_max_regex_bytes", "filter_max_widen_passes", "filter_row_cache_max_bytes", "filter_row_cache_max_entries", "fts_block_merge_threshold", "fts_block_split_threshold", "fts_block_target_postings", "fts_enable_delta_rebalance", "fts_max_term_blocks_touched_per_doc_update", "otel_enabled", "otel_exporter_otlp_endpoint", "otel_metric_export_interval_ms", "otel_sample_ratio", "otel_service_name", "query_ann_enabled", "queue_broker_url", "storage_bucket", "storage_endpoint", "storage_provider", "storage_region", "storage_simulated_latency_ms", "wal_queue_background_drain_enabled", "wal_queue_background_drain_interval_ms", "wal_worker_build_ann", "wal_worker_build_fts"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> RuntimeConfigResponse:
        """Create an instance of RuntimeConfigResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "additional_properties"
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of filter_cache_metrics
        if self.filter_cache_metrics:
            _dict['filter_cache_metrics'] = self.filter_cache_metrics.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> RuntimeConfigResponse:
        """Create an instance of RuntimeConfigResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return RuntimeConfigResponse.parse_obj(obj)

        _obj = RuntimeConfigResponse.parse_obj({
            "ann_bucket_fetch_concurrency": obj.get("ann_bucket_fetch_concurrency"),
            "bind_addr": obj.get("bind_addr"),
            "filter_cache_metrics": FilterCacheMetricsSnapshot.from_dict(obj.get("filter_cache_metrics")) if obj.get("filter_cache_metrics") is not None else None,
            "filter_cluster_cache_max_bytes": obj.get("filter_cluster_cache_max_bytes"),
            "filter_cluster_cache_max_entries": obj.get("filter_cluster_cache_max_entries"),
            "filter_max_glob_bytes": obj.get("filter_max_glob_bytes"),
            "filter_max_regex_bytes": obj.get("filter_max_regex_bytes"),
            "filter_max_widen_passes": obj.get("filter_max_widen_passes"),
            "filter_row_cache_max_bytes": obj.get("filter_row_cache_max_bytes"),
            "filter_row_cache_max_entries": obj.get("filter_row_cache_max_entries"),
            "fts_block_merge_threshold": obj.get("fts_block_merge_threshold"),
            "fts_block_split_threshold": obj.get("fts_block_split_threshold"),
            "fts_block_target_postings": obj.get("fts_block_target_postings"),
            "fts_enable_delta_rebalance": obj.get("fts_enable_delta_rebalance"),
            "fts_max_term_blocks_touched_per_doc_update": obj.get("fts_max_term_blocks_touched_per_doc_update"),
            "otel_enabled": obj.get("otel_enabled"),
            "otel_exporter_otlp_endpoint": obj.get("otel_exporter_otlp_endpoint"),
            "otel_metric_export_interval_ms": obj.get("otel_metric_export_interval_ms"),
            "otel_sample_ratio": obj.get("otel_sample_ratio"),
            "otel_service_name": obj.get("otel_service_name"),
            "query_ann_enabled": obj.get("query_ann_enabled"),
            "queue_broker_url": obj.get("queue_broker_url"),
            "storage_bucket": obj.get("storage_bucket"),
            "storage_endpoint": obj.get("storage_endpoint"),
            "storage_provider": obj.get("storage_provider"),
            "storage_region": obj.get("storage_region"),
            "storage_simulated_latency_ms": obj.get("storage_simulated_latency_ms"),
            "wal_queue_background_drain_enabled": obj.get("wal_queue_background_drain_enabled"),
            "wal_queue_background_drain_interval_ms": obj.get("wal_queue_background_drain_interval_ms"),
            "wal_worker_build_ann": obj.get("wal_worker_build_ann"),
            "wal_worker_build_fts": obj.get("wal_worker_build_fts")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


